execute pathogen#infect()

syntax on
set number
set ruler
set noerrorbells
set cmdheight=2 " set commandbar height

set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch

set tabstop=2 " default to ruby style
set shiftwidth=2 
set expandtab
set autoindent

autocmd FileType java setlocal tabstop=4 shiftwidth=4 " override for java
autocmd FileType go setlocal noexpandtab tabstop=4 shiftwidth=4 " override for go
autocmd FileType c setlocal noexpandtab tabstop=8 shiftwidth=8 " override for c

command Rtree NERDTree

map <F2> :set expandtab<CR>:set tabstop=2<CR>:set shiftwidth=2<CR>
nnoremap <F3> :set number!<CR>:set paste!<CR>
map <F4> :set tabstop=4<CR>:set shiftwidth=4<CR>
map <F5> :vsplit<CR>
map <F6> :split<CR>
map <F8> :set tabstop=8<CR>:set shiftwidth=8<CR>
map <F9> :set background=dark<CR>
map <F10> :set background=light<CR>
map <F11> :colorscheme darkblue<CR>:set background=dark<CR>
map <F12> :colorscheme desert<CR>:set background=light<CR>
